name: flutter_voice_messenger
description: "A new Flutter project for voice messaging."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.5+1
  http: ^1.6.0
  intl: ^0.20.2
  path_provider: ^2.1.3
  card_swiper: ^3.0.1

  # Audio
  record: ^6.1.2 # Using a specific version to ensure compatibility
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_app_check_web: ^0.2.2


  # Other
  url_launcher: ^6.3.2
  mime: ^1.0.5
  audioplayers: ^6.5.1
  audio_session: ^0.2.2
  cloud_functions_web: ^5.1.0
  just_audio_web: ^0.4.16
  just_audio: ^0.10.5
  firebase_ai: ^3.6.0
  carousel_slider: ^5.1.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
