name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.38
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  record: ^6.1.2
  audioplayers: ^6.0.0
  http: ^1.6.0
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
